#!/usr/bin/env python                                                                                                                                        
# -*- coding:utf-8 -*-

# ------------------------------------------------------------------------
# 作者：王旭
# 邮箱：wangxu03@youku.com
# 日期：
# ------------------------------------------------------------------------
# 功能：
# ------------------------------------------------------------------------

import sys
import time
reload(sys)
sys.setdefaultencoding('utf-8')


########## main方法 ##########
def main(argv):

    print '========== start at %s ==========' % time.strftime("%Y-%m-%d %H:%M:%S",time.localtime(time.time()))
    ########## 方法开始 ##########



    ########## 方法结束 ##########
    print '========== end at %s ==========' % time.strftime("%Y-%m-%d %H:%M:%S",time.localtime(time.time()))


########## 脚本入口 ##########
if __name__ == '__main__':
    main(sys.argv)
